application: wide-exchanger-382
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'myproject.settings'
  DATABASE_URL: 'mysql://root@wide-exchanger-382:red/appengine_blog'

handlers:
- url: /static
  static_dir: static